server:
  port: 8888   # ⚙️ Puerto estándar del Config Server

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabrizzio122/DISTRI.git  # Repositorio central
          searchPaths: config-data                         # Carpeta donde estarán los YML de cada microservicio
          default-label: main                              # Rama principal
  security:
    user:
      name: root                                           # Usuario de acceso al Config Server
      password: 123456